### ISSUE TITLE
Can't download learning Deneb - Contoso 1M - git.pbix

### ISSUE THREAD

**Issue by Klimkiv** [tomatminceddata/learningdeneb#2]
Please, can the file be downloaded?

**Comment by tomatminceddata** [comment]
What is the issue, do you receive an error when hitting the download button?

**Comment by Klimkiv** [comment]
No messages, just no download

пт, 15 нояб. 2024 г., 15:28 Tom Martens ***@***.***>:

**Comment by tomatminceddata** [comment]
Please confirm that the "download button" is not available:
<img width="1707" alt="image" src="https://github.com/user-attachments/assets/eb7acd15-c534-4fae-b32f-6674269c2224">

**Comment by Klimkiv** [comment]
Tom, thank you
sorry my english, there is no download as a process, but I did download from my home pc.

**Comment by tomatminceddata** [comment]
I'm happy that you have the file now. Enjoy the weekend and some Deneb 😉
